### PR TITLE
Python and docker fixes

### PR DESCRIPTION
**Pull request by robsyme**
Hi COSMO authors

At the moment, I don't think there is a way of users knowing what software is being loaded inside the Docker container used to run each of the COSMO tasks. Included in this PR is a minimal Dockerfile that can be used to build an image suitable for the docker tasks.

Also included is a change to use the python script bundled in this repository rather than the docker image for the method 2 process.

### CODE REVIEW

**Comment by toddcreasy** [comment]
Hi COSMO authors,

I was wondering if you had a timeline where this might get merged. This is causing a few errors with our nextflow tower pipeline.

Thanks!

-todd

**Comment by drpatelh** [comment]
Singularity profile added in https://github.com/robsyme/COSMO/pull/1

**Comment by drpatelh** [comment]
Please close this PR and merge https://github.com/bzhanglab/COSMO/pull/7 instead. All changes here have been added there.

**Comment by zhiaos** [comment]
Changes have been included in #7

**Pull request closed without merging**
